### ISSUE TITLE
It seems your package is broken??

### ISSUE THREAD

**Issue by JonathanLehner** [lucleray/tfjs-lambda#6]
I tried different versions and also tfjs-lambda, but it all gives the error on Zeit now. Cannot use my api anymore!! You shouldn't have fixed the tfjs-converter version to latest, which apparently caused it to break.

START RequestId: d2f72658-c095-47f4-b1a0-87fb5bd73c92 Version: $LATEST
                          2019-11-16T23:43:59.070Z	d2f72658-c095-47f4-b1a0-87fb5bd73c92	TypeError: Cannot read property 'T' of undefined
                              at OperationMapper.getDtypeParam (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/operations/operation_mapper_json.js:203:26)
                              at /tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/operations/operation_mapper_json.js:150:43
                              at Array.reduce (<anonymous>)
                              at OperationMapper.mapNode (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/operations/operation_mapper_json.js:112:44)
                              at /tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/operations/operation_mapper_json.js:57:36
                              at Array.reduce (<anonymous>)
                              at OperationMapper.transformGraph (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/operations/operation_mapper_json.js:56:29)
                              at FrozenModel.<anonymous> (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model_json.js:128:113)
                              at step (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model_json.js:32:23)
                              at Object.next (/tmp/tfjs-node/node_modules/@tensorflow/tfjs-converter/dist/src/executor/frozen_model_json.js:13:53)
                          2019-11-16T23:43:59.070Z	d2f72658-c095-47f4-b1a0-87fb5bd73c92	{ Error: The model could not be loaded (bad_request)
                              at createError (/var/task/api/lib/error.js:25:10)
                              at BadRequestError (/var/task/api/lib/error.js:41:3)
                              at loadModel (/var/task/api/index.js:28:11)
                              at <anonymous>
                              at process._tickDomainCallback (internal/process/next_tick.js:228:7)
                            statusCode: 400,
                            error: 
                             { code: 'bad_request',
                               message: 'The model could not be loaded' } }
                          END RequestId: d2f72658-c095-47f4-b1a0-87fb5bd73c92
                          REPORT RequestId: d2f72658-c095-47f4-b1a0-87fb5bd73c92

**Comment by JonathanLehner** [comment]
I just tried to load an ordinary GraphModel. It works locally without any errors

**Comment by lucleray** [comment]
Hi, thanks for the report.

I'll have a look at it as soon as I can 🙂
